Création du texte qui introduit le dépot GitHub du CQEN
CQEN-QDCE/.github pull request #1
Opened 2023-12-14 20:47 UTC by flihp27

2023-12-15 14:08 UTC, gagf01 requested changes

2023-12-15 14:08 UTC, gagf01 commented on profile/README.md
> +[![License](https://img.shields.io/badge/Licence-LiLiQ--P-blue)](https://github.com/CQEN-QDCE/.github/blob/main/LICENCE.md)
A-t-on besoin d'une licence et du badge pour ce contenu?

2023-12-15 14:08 UTC, gagf01 commented on profile/README.md
> +![MCN](https://github.com/CQEN-QDCE/.github/blob/main/images/mcn.png)
```suggestion
[![MCN](https://github.com/CQEN-QDCE/.github/blob/main/images/mcn.png)](https://www.quebec.ca/gouvernement/ministere/cybersecurite-numerique)
```

2023-12-15 14:08 UTC, gagf01 commented on profile/README.md
> +Le Centre québécois d’excellence numérique (CQEN) est une unité du ministère de la Cybersécurité et du Numérique (MCN) consacrée exclusivement à la transformation numérique gouvernementale. Sa missio
```suggestion
Le Centre québécois d’excellence numérique (CQEN) est une unité du ministère de la Cybersécurité et du Numérique (MCN) consacrée exclusivement à la transformation numérique gouvernementale. Sa mission est d’accélérer et de simplifier cette dernière en favorisant le partage et la collaboration. L’un des moyens mis à sa disposition est l’innovation. Celle-ci s’appuie sur la recherche et le développement à travers l’expérimentation et le prototypage pour comprendre les tenants et aboutissants associés à la mise en place de nouvelles technologies ou façons de faire innovantes et émergentes dans le numérique. Ces expérimentations sont réalisées sous le couvert de l’un ou les deux axes suivants :
```

2023-12-15 14:08 UTC, gagf01 commented on profile/README.md
> +Cette organisation contient les dépôts du CQEN ainsi que de projets et groupes de travail avec lesquels nous collaborons.
Est-ce qu'on devrait développer sur la démarche d'expérimentation et sur le fait que l'organisation contiendra surtout les dépôts d'expérimentation?

2023-12-15 14:08 UTC, gagf01 commented on profile/README.md
> +- [DevaaS](https://codeready-openshift-workspaces.apps.exp.openshift.cqen.ca/dashboard/)
Je ne suis pas fan des sigles en 'aas' mais je comprend qu'on ne peut pas vraiment nommer de fournisseurs ici? Est-ce qu'on peut s'entendre sur:
* Outil de cadencement Agile (Ajouter Taïga?)
* Zone d'accueil infonuagique
* Plateforme de développement conteneurisé
* Environnement de développement infonuagique

2023-12-19 01:46 UTC, flihp27 commented on profile/README.md
> +[![License](https://img.shields.io/badge/Licence-LiLiQ--P-blue)](https://github.com/CQEN-QDCE/.github/blob/main/LICENCE.md)
Pourquoi pas, si quelqu'un décide de réutiliser le texte, on confirme qu'il est libre d'utilisation et on montre l'exemple.

2023-12-19 01:49 UTC, flihp27 commented on profile/README.md
> +Cette organisation contient les dépôts du CQEN ainsi que de projets et groupes de travail avec lesquels nous collaborons.
Accepté

2023-12-19 01:51 UTC, flihp27 commented on profile/README.md
> +- [DevaaS](https://codeready-openshift-workspaces.apps.exp.openshift.cqen.ca/dashboard/)
Accepté

2023-12-19 18:59 UTC, gagf01 approved these changes

2023-12-20 02:58 UTC, merged